#!/usr/bin/env ruby

require_relative 'lib/anz_bank_csv_cleaner'

if (ARGV.length != 1) then
  puts "anz-csv-export-cleaner [path to import CSV]"
  exit
end

import_path = ARGV[0]
export_path = "#{import_path.split('.')[-2]}.cleaned.csv"

export_cleaner = ANZBankCSVCleaner.new(import_path: import_path, export_path: export_path)
export_cleaner.run

puts "Export complete."
